### ISSUE TITLE
What the right way to "clean up" after exception during state process?

### ISSUE THREAD

**Issue by dany52** [Beh01der/EasyFlow#19]
Hi, Andrey

Firstly, thank you for very good library.
So powerfull and simple.

But I can't figure out the right way to handle exception during state process. 

What the right way to "clean up" after exception?
In some situation I wanna to revert to previous state. In others I prefer restart flow.  How make this?

**Comment by Beh01der** [comment]
Hi Dany,

Exception should be handled in your code.
Then, if exception happened, there must be some **event** defined that will be triggered in this case.
That event can be connected to the previous **state** like this:
```
   on(someEvent).to(CURRENT_STATE).transit(
      on(success).to(NEXT_STATE),
      on(error).to(CURRENT_STATE)
   )
```
Instead of **CURRENT_STATE** you can go to any other state within current FSM.

**Comment by dany52** [comment]
Hi, Andrey

Thanks I actually realized that in the "FSM world"  is the only correct way :)
